import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, readFile, rm, stat, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { Authorizations } from '../src/bridge/authorizations.js';
import { startBridge } from '../src/bridge/server.js';

const context = { document: 'Same file name', page: 'Page', pageId: '0:1', selection: [] };
test('one binding survives bridge restart, resumes idempotently, and scopes commands to distinct files', async t => {
  const dir = await mkdtemp(join(tmpdir(), 'figma-authorization-'));
  const authorizationPath = join(dir, 'authorizations.json');
  let bridge = await startBridge({ port: 0, authorizationPath, pairingCode: '123456' });
  t.after(async () => { await bridge.close(); await rm(dir, { recursive: true, force: true }); });
  const post = async (path: string, data: unknown, token = '') => {
    const response = await fetch(`http://127.0.0.1:${bridge.port}${path}`, { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` }, body: JSON.stringify(data) });
    return { status: response.status, ...await response.json() as any };
  };
  const pair = await post('/pair', { code: '123456', context, instanceId: 'file-a' });
  assert.equal(pair.ok, true);
  assert.ok(!(await readFile(authorizationPath, 'utf8')).includes(pair.resumeToken));
  assert.equal((await stat(authorizationPath)).mode & 0o777, 0o600);
  assert.equal((await post('/pair', { code: '123456', context })).error.code, 'PAIRING_EXPIRED');
  const previousSession = pair.sessionId;
  const oldCLI = bridge.token;
  await bridge.close(); bridge = await startBridge({ port: 0, authorizationPath });
  assert.notEqual(bridge.token, oldCLI);
  assert.equal((await post('/plugin/heartbeat', { context }, pair.token)).status, 401);
  const a = await post('/resume', { context, instanceId: 'file-a-reopened' }, pair.resumeToken);
  assert.equal(a.ok, true); assert.notEqual(a.sessionId, previousSession);
  const retry = await post('/resume', { context, instanceId: 'file-a-reopened' }, pair.resumeToken);
  assert.equal(retry.sessionId, a.sessionId); assert.equal(retry.token, a.token);
  const b = await post('/resume', { context, instanceId: 'file-b' }, pair.resumeToken);
  assert.equal(b.ok, true); assert.notEqual(b.sessionId, a.sessionId);
  assert.equal(bridge.broker.list().length, 2);
  const command = { id: 'distinct-file-command', method: 'document', params: {}, timeoutMs: 1000 };
  assert.equal((await post('/commands', command, pair.resumeToken)).status, 401);
  assert.equal((await post('/resume', { context, instanceId: 'cli-as-plugin' }, bridge.token)).status, 401);
  assert.equal((await post('/commands', command, bridge.token)).error.code, 'AMBIGUOUS_SESSION');
  const submitted = post('/commands', { ...command, sessionId: b.sessionId }, bridge.token);
  const poll = await post('/plugin/poll', {}, b.token);
  assert.equal(poll.command.id, command.id);
  assert.equal((await post('/plugin/result', { id: command.id, ok: true, result: 'wrong file' }, a.token)).error.code, 'UNKNOWN_REQUEST');
  await post('/plugin/result', { id: command.id, ok: true, result: 'file b' }, b.token);
  assert.equal((await submitted).result, 'file b');
  await post('/plugin/disconnect', {}, a.token);
  const reopened = await post('/resume', { context, instanceId: 'file-a-next-launch' }, pair.resumeToken);
  assert.equal(reopened.ok, true); assert.equal(bridge.broker.list().length, 2);
  await post('/forget', {}, pair.resumeToken);
  assert.equal(bridge.broker.list().length, 0);
  assert.equal((await post('/resume', { context, instanceId: 'revoked' }, pair.resumeToken)).error.code, 'AUTHORIZATION_REVOKED');
  await bridge.close(); bridge = await startBridge({ port: 0, authorizationPath });
  assert.equal((await post('/resume', { context, instanceId: 'still-revoked' }, pair.resumeToken)).status, 401);
});

test('authorization writes serialize, preserve unrelated clients, and reject corrupt or unwritable storage', async t => {
  const dir = await mkdtemp(join(tmpdir(), 'figma-store-')); t.after(() => rm(dir, { recursive: true, force: true }));
  const path = join(dir, 'authorizations.json');
  const store = await Authorizations.open(path);
  const tokens = await Promise.all([store.issue(), store.issue(), store.issue()]);
  let restored = await Authorizations.open(path);
  for (const token of tokens) assert.ok(restored.identify(token));
  await restored.revoke(restored.identify(tokens[0])!);
  restored = await Authorizations.open(path);
  assert.equal(restored.identify(tokens[0]), undefined); assert.ok(restored.identify(tokens[1]));
  const broken = await Authorizations.open(join(dir, 'missing', 'authorizations.json'));
  await assert.rejects(broken.issue(), { code: 'AUTH_STORE_WRITE_FAILED' });
  await writeFile(path, 'synthetic-corrupt-state');
  await assert.rejects(Authorizations.open(path), { code: 'AUTH_STORE_UNREADABLE' });
  assert.equal(await readFile(path, 'utf8'), 'synthetic-corrupt-state');
});
